### ISSUE TITLE
Subir el código inicial al proyecto

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#1]
Necesitamos que @YellowZaki suba el código que tiene almacenado en su equipo para poder empezar a trabajar en el proyecto de forma conjunta.

**Comment by YellowZaki** [comment]
Hecho

**Comment by profeIAP** [comment]
Os anoto a los dos porque considero que la ayuda de @carlosaj98 ha sido inestimable para su finalización.

**Comment by profeIAP** [comment]
Por cierto... buen trabajo ;)
