### ISSUE TITLE
Invocar el método 'limpiar' correctamente

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#10]
Una vez implementada la tarea #9 modificar el [modo en el que se utiliza en el fichero html](https://github.com/julioosos/2BACHTIC/blob/2eb13ecc6e71d79b5db1fd15cdd5f8f4fe7785de/index.html#L47) de forma que le proporcione el ID de la lista de valores en lugar de la referencia que se usa actualmente.

**Comment by carlosaj98** [comment]
Ya la he terminao

**Comment by profeIAP** [comment]
Poco a poco @carlosaj98, no te agobies que estamos empezando (ya cogerás velocidad de "crucero")
Simplemente has cambiado el ID (que de por si ya era correcto) y has dejado el document.getElementByID

**Comment by carlosaj98** [comment]
Ya la he terminado

**Comment by profeIAP** [comment]
Sí señor, buen trabajo @carlosaj98
