### ISSUE TITLE
Los valores desaparecen al pulsar "enter"

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#12]
Si tienes varios valores en la lista y pulsas la tecla del "retorno de carro" desaparecen por arte de "magia".

**PISTA:** se está intentando enviar el formulario al servidor y éso provoca que se cargue nuevamente.

**Comment by Mahc99** [comment]
Terminada ;)

**Comment by profeIAP** [comment]
Y bien terminada que está... buen trabajo Migue, has abierto la puerta a nuevas funcionalidades en el formulario, gracias.
