### ISSUE TITLE
Impedir que el usuario pueda editar la caja de mensajes

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#16]
Evitar que el usuario pueda modificar el contenido del textarea en el que el sistema muestra sus mensajes de progreso

Observa la siguiente imagen en la que me he puesto a escribir "libremente" lo que me ha parecido bien

![captura de pantalla de 2016-10-21 21-14-32](https://cloud.githubusercontent.com/assets/16881846/19608773/9114b6e6-97d3-11e6-96c1-08ec72a92958.jpg)

**Comment by Mahc99** [comment]
Facil, sencillo y para toda la "familia"

**Comment by profeIAP** [comment]
Y también limpio y eficiente... no olvides dichos "parámetros" ;)
Buen trabajo Migue.
