### ISSUE TITLE
Centrar el título del formulario

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#17]
Actualmente está levemente desplazado a la izquierda.
Hacer que coincida con el cuerpo del formulario

![captura de pantalla de 2016-10-24 11 30 25](https://cloud.githubusercontent.com/assets/16881846/19640524/6e8664c4-99dd-11e6-86e8-9e3224b94279.png)

**Comment by julioosos** [comment]
ya ta

**Comment by profeIAP** [comment]
Lo sigo viendo "torcido" @julioosos 
¿Has probado el resultado antes de subirlo al repositorio?

**Comment by profeIAP** [comment]
Obsérvese que mientras que el formulario se mantiene centrado, el título se coloca donde le parece bien pero, desde luego, no en el centro :)

![captura de pantalla de 2016-10-28 16-48-36](https://cloud.githubusercontent.com/assets/16881846/19810626/7b3b0270-9d2e-11e6-8394-f6f12af92906.jpg)

**Comment by julioosos** [comment]
no se si lo recuerdas pero al cambiar la resolucion lo que salia centrado era el titulo y el formulario no

**Comment by profeIAP** [comment]
Sí que lo recuerdo, por eso me sorprende que se comporte como se observa en la captura de pantalla.

**Comment by julioosos** [comment]
Lo corregire

**Comment by julioosos** [comment]
ya esta

**Comment by julioosos** [comment]
ya

**Comment by profeIAP** [comment]
Veo que al final te enteraste de la solución XD

Ya funciona correctamente (aunque ha sido efímero porque alguien parece habérselo cargado en commits posteriores), gracias Julio
