### ISSUE TITLE
Indentar correctamente el contenido del fichero html

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#18]
Usar algún "pretty printer" de HTML para que el código quede correctamente indentado y podamos ver sin dificultad cómo están anidadas las distintas etiquetas que lo componen

**Comment by jcarlos99** [comment]
He hecho pretty printer con: [](http://jsbeautifier.org/)

**Comment by jcarlos99** [comment]
He hecho pretty printer con [http://jsbeautifier.org/](url)

**Comment by profeIAP** [comment]
Quedamos a la espera de que subas los cambios en html.
Gracias por dejar anotada la herramienta utilizada.

**Comment by profeIAP** [comment]
Pefecto Juan Carlos, ¡vamos por la siguiente tarea!
