### ISSUE TITLE
Ubicar correctamente el título de la web

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#19]
El [siguiente fragmento de código](https://github.com/julioosos/2BACHTIC/blob/7d068dd97a57879285cb036b908a03c72375e9d1/index.html#L7) debe estar dentro de las etiquetas <body> de nuestro html (en lugar de en el <head> como está ahora)

**Comment by julioosos** [comment]
ya ta

**Comment by profeIAP** [comment]
Po no tá... para que sea considerado un html bien formado, debe incluirse **dentro** del html y no _entre_ el head y el body :)

**Comment by julioosos** [comment]
corregido

**Comment by profeIAP** [comment]
Obsérvese que sólo está centrado en las pantallas de los portátiles (y no en el resto de la _humanidad_)

![captura de pantalla de 2016-10-28 10 40 14](https://cloud.githubusercontent.com/assets/16881846/19800317/84ffa730-9cfb-11e6-86bc-426ff06917c3.png)

**Comment by profeIAP** [comment]
Perfecto Julio, ahora sí... buen trabajo
