### ISSUE TITLE
Cambiar texto botón al seleccionar valores en la lista

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#24]
Tras implementar la tarea #22 se requiere que el texto del botón pase de _Añadir_ a _Editar_

**Comment by YellowZaki** [comment]
Se cambia Añadir --> Editar estéticamente al seleccionar el item. (una vez se cambia a Editar, el botón sigue funcionando como Añadir)
Hay que pensar cómo salir del estado de editar para agregar la funcionalidad de Editar.

**Comment by profeIAP** [comment]
Gracias por dejar anotado el problema que mencionamos en clase Alberto.

Se observa que realmente el botón cambia estéticamente (y francamente es muy útil la ayuda visual que has implementado) pero no cambia el texto de "Añadir" a "Editar" como se solicita en la especificación de la tarea.

Agradecería resolvieses el detalle que nos falta para dar por cerrada la incidencia.

**Comment by YellowZaki** [comment]
Sí se cambiaba pero tras algún cambio realizado por otro compañero dejó de funcionar (al igual que el estilo del botoón ahora está feo)

**Comment by profeIAP** [comment]
Sospechaba que era así y [opté por cambiar a tu commit](https://github.com/profeIAP/panelDeControl/wiki#utilizar-versi%C3%B3n-anterior-del-proyecto) (ignorando los cambios posteriores de tus compañeros) y seguía sin funcionar correctamente

**Comment by YellowZaki** [comment]
Que lo arregle @Mahc99

**Comment by YellowZaki** [comment]
Vale, ya lo arreglo yo.
He revertido el código que cambió Miguel Ángel:
![captura de pantalla de 2016-11-03 13 31 26](https://cloud.githubusercontent.com/assets/13599841/19965995/f6c7503e-a1c9-11e6-82a9-d786949c6641.png)

**Comment by profeIAP** [comment]
Poco ha durado la alegría: luego ha llegado @julioosos y se lo ha vuelto a "merendar"
