### ISSUE TITLE
Falta barra de scroll en la lista de valores

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#27]
Cuando se insertan un número elevado de valores en el formulario no aparece la correspondiente barra de scroll.

![captura de pantalla de 2016-10-27 14 01 29](https://cloud.githubusercontent.com/assets/16881846/19766428/093a6638-9c4e-11e6-8e46-a7bacd788836.png)

**Comment by profeIAP** [comment]
Vale, observo que no salía por el cambio estético que le habías aplicado a la lista de valores.
Tengo una duda "moral":
1. Crear una nueva tarea para que la barra de scroll no aparezca de forma innecesaria como ocurre actualmente cuando hay pocos valores
2. Cambiar el nivel de dificultad de la tarea (cambiar un ancho en la CSS realmente es trivial una vez que sabes qué debes hacer claro está)

Abro la tarea simplemente para que decidas qué consideras más ético y oportuno, Alberto (cualquier otro integrante del equipo de desarrollo, siempre que sea de forma constructiva, está invitado a opinar)

**Comment by YellowZaki** [comment]
No se puede ocultar la base sobre la que aparece la barra. Tampoco se puede cambiar su color en firefox (para cada navegador hay una propiedad diferente: http://stackoverflow.com/questions/9251354/css-customized-scroll-bar-in-div)

**Comment by profeIAP** [comment]
Optaré pues a bajar la dificultad de la tarea y dejarlo como está (feo pero funcional)

Si alguien consigue o se anima a dejarlo "fino" que avise y le creo una nueva tarea de nivel reto :)
