### ISSUE TITLE
Evitar cambio puntero del ratón

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#29]
Cuando se coloca el ratón fuera de la zona ocupada por el formulario (da igual izquierda que derecha), el puntero del ratón pasa a convertirse en una mano (en lugar de la flecha habitual)

Dicho comportamiento induce a error (es como si pudiésemos hacer click en esa zona) por lo que debe evitarse.

**Comment by carlosaj98** [comment]
YA ta solucionao
