### ISSUE TITLE
Añadir librería tooltips

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#31]
La idea es contar con la posibilidad de mostrar ayuda al usuario cuando coloque el ratón encima de cualquiera de los elementos de nuestro formulario.

![](http://www.jomendez.com/wp-content/uploads/2016/06/css-tooltip.png)

Idealmente se optará por una solución que no requiera jQuery (de momento, estamos huyendo de ella) y, si fuese posible, que no necesite ni javascript (HTML5 es tu "amigo")

**Comment by julioosos** [comment]
ya ta

**Comment by profeIAP** [comment]
Sea, es funcional.
