### ISSUE TITLE
Permitir reorganizar los elementos de la lista

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#32]
Teniendo en cuenta que en algunos de los algoritmos que implementaremos la posición de los elementos será importante, se necesita poder cambiar la posición de los valores introducidos en la lista.

Una posible solución sería [la librería que enlazo](https://www.tomred.net/css-html-js/reorder-option-elements-of-an-html-select.html) pero, si fuese posible, sería interesante poder hacerlo arrastrándolos directamente en lugar de tener que incluir botones en el formulario para subir/bajar los elementos.

**Comment by Rafaelcraftero** [comment]
¿como puedo conseguir que cambia de posición en la tabla con solo cogerlo y soltarlo? ¿Por donde debo empezar? y en donde debo buscar. Yo he buscado [aquí](https://www.html5rocks.com/es/tutorials/dnd/basics/) pero no es igual dado que son datos los que se mueven si no columnas

**Comment by profeIAP** [comment]
Muy interesante la propuesta D.Rafael pero, desgraciadamente, no nos sirve.
Le recomendaría estudiar la librería que enlazo en la descripción de la tarea o, si le resultase más sencillo, [esta otra librería](https://github.com/sitepoint-editors/accessible-drag-and-drop.git)

**Comment by Rafaelcraftero** [comment]
Hay un problema. En el primer enlace es como y donde poner el up and down sin que funcione el editar dado que lo único que hace es añadir otra vez lo mismo.  En el segundo enlace que me has pasado no sirve, dado que solo cambia las cajas de un lugar a otro, no sube ni baja. Además no sé el porqué no arrastra la option que crea el select. Lo intente quitando la multiple selection e intentar arrastrar de uno en uno y tampoco funciona, cuando pasas por encima el cursor con el botón izq presionado selecciona el que tiene debajo y quita la selección del que presionaste en un principio. Ese es el primer problema. Una vez funcione el arrastrar para objetos de 1 en 1.  Para que funcionase en conjunto con selección multiple,  lo que habría que hacer es que el editor cree como una especie de celda o bloque en el que estuvieran todos y que después cuando le des a aceptar(que no hay botón todavía) que se quita el bloque o celda. Se volviera a celdas de 1 en 1. A día de hoy no se como hacerlo ni con los enlaces que me has pasado. Creo que es imposible con lo que tenemos del proyecto hecho de hoy en día. Para que consiguiese que funcionara tendría que hacer 4 o 5 retos yo solo, poniendo una ingente cantidad de tiempo. Y creo que por simplemente por 2 puntos no merece la pena. Intenta ayudarme, dado que estoy empeñado en acabarlo dado que para llegar a estas conclusiones y aprender como funcionan las cosas he tardado sin exagerar 20 horas sin llegar a nada y que de tanto trastear buscar por internet, ya me se los entresijos de html5.

**Comment by Rafaelcraftero** [comment]
Si me pudieras responder te lo agradecería

**Comment by profeIAP** [comment]
D. Rafael, le contesté en persona cuando me preguntó pero le dejaré un resumen por escrito ya que muestra interés: los enlaces que incluyo en la descripción de la tarea son meras posibilidades de solución; como reto que es puede ocurrir que fuese "imposible" resolverlo o, por lo menos, bastante complejo. Si considera que no puede resolverlo, le recomendaría optar por otra tarea más acorde a sus posibilidades y/o le costase menos trabajo resolver.

**Comment by profeIAP** [comment]
Sin entrar en detalles estéticos D.Rafael le ha quedado realmente bien.
Buen trabajo
