### ISSUE TITLE
Pretty printer HTML para Geany

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#39]
Buscar, probar y documentar someramente (en un comentario de esta tarea sería suficiente) cómo instalar (si existe) un complemento de Geany que permita indentar correctamente el contenido de cualquier fichero html que estemos editando

**Comment by carlosaj98** [comment]
[Javasript beautify](http://www.danstools.com/javascript-beautify/) (pone javascript pero he probado con html y sirve igual)

**Comment by profeIAP** [comment]
Igual le interesa a @jcarlos99 pero la idea es utilizar un complemento de Geany y no una herramienta online como la que has indicado.

**Comment by profeIAP** [comment]
¿Por qué has abandonado la tarea @carlosaj98? 
Es más fácil de lo que realmente aparenta

**Comment by Rafaelcraftero** [comment]
te refieres a [esto](https://plugins.geany.org/jsonprettifier.html) ?

**Comment by profeIAP** [comment]
No, ese plugin es para JSON y nosotros buscamos uno de html

**Comment by Rafaelcraftero** [comment]
Entonces si no era eso será [esto](https://plugins.geany.org/pretty-printer.html)

**Comment by profeIAP** [comment]
Es posible pero, como no hay información en la web que has enlazado, te va a tocar instalarlo y contarnos si hace lo pedido.

Suerte D. Rafael
