### ISSUE TITLE
Cambiar el nombre del formulario

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#4]
Quitar el nombre de Alberto
![captura de pantalla de 2016-10-20 14 00 18](https://cloud.githubusercontent.com/assets/16881846/19558999/b39a6d70-96cd-11e6-9672-581ed1667b64.png)

Poner en su lugar "Formulario web" (se admite ser creativo a la hora de poner el nuevo nombre)

**Comment by julioosos** [comment]
ya ta

**Comment by profeIAP** [comment]
Perfect @julioosos 

No diré que te ha quedado "precioso" (porque, de momento el formulario es bastante feo) pero has cumplido con lo pedido.

Buen trabajo, vamos por la próxima tarea (... que quede libre ;) )
