### ISSUE TITLE
Organizar código en carpetas

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#5]
Mover los ficheros _.js_ y _.css_ a carpetas de nombre _js_ y _css_ respectivamente modificando el código de html ([aquí](https://github.com/julioosos/2BACHTIC/blob/1d2e87794b2158c74b3751029d6edee01a744ba3/index.html#L6) y [aquí](https://github.com/julioosos/2BACHTIC/blob/1d2e87794b2158c74b3751029d6edee01a744ba3/index.html#L8)) para que enlace a la nueva ubicación.

**Comment by Mahc99** [comment]
Con algunos commits de mas pero creo q esta terminada =P

**Comment by profeIAP** [comment]
Algún que otro commit nos ha sobrado y (como era previsible) algo de código se ha perdido por el camino (ver tarea #3) pero ha quedado muy bien @Mahc99 (demasiado para el tiempo que hace que no usáis git ;) )
