### ISSUE TITLE
Usar copia local del favIcon

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#6]
Crear carpeta _img_ en el proyecto donde ubicaremos [el favIcon que se está utilizando actualmente](https://github.com/julioosos/2BACHTIC/blob/1d2e87794b2158c74b3751029d6edee01a744ba3/index.html#L7)

Actualizar el código html para que se use la copia local que hemos realizado

**Comment by carlosaj98** [comment]
Terminado

**Comment by profeIAP** [comment]
Desgraciadamente no puedo estar de acuerdo.

Observa que [se sigue utilizando la versión web del favicon](https://github.com/julioosos/2BACHTIC/blob/7d068dd97a57879285cb036b908a03c72375e9d1/index.html#L7)

**Comment by carlosaj98** [comment]
terminao

**Comment by profeIAP** [comment]
Desgraciadamente sólo debe aparecer el favicon en tu equipo (observa que no estás usando rutas relativas sino absolutas **a tú equipo**)

![captura de pantalla de 2016-10-27 16-34-59](https://cloud.githubusercontent.com/assets/16881846/19771596/b2f8f116-9c63-11e6-8c4f-3c86c085ddc7.jpg)

**Comment by carlosaj98** [comment]
Ahora si

**Comment by profeIAP** [comment]
Estoy de acuerdo contigo Carlos, ahora sí que se ve "bien"
Sigue así
