### ISSUE TITLE
Modificar el método 'limpiar' de una lista

### ISSUE THREAD

**Issue by profeIAP** [julioosos/2BACHTIC#9]
Modificar [el método limpiar](https://github.com/julioosos/2BACHTIC/blob/2eb13ecc6e71d79b5db1fd15cdd5f8f4fe7785de/script.js#L2) de modo que acepte como parámetro una cadena de texto que indique el ID de la lista de la que deben borrarse **todas** las entradas (debe comportarse tal y como lo hace actualmente [el método 'procesar'](https://github.com/julioosos/2BACHTIC/blob/master/script.js#L24)) en lugar de la referencia al combo que recibe actualmente.

**Comment by carlosaj98** [comment]
Ya la he terminado

**Comment by profeIAP** [comment]
Te he dejado un [comentario en el código qué está fallando](https://github.com/julioosos/2BACHTIC/commit/648c56338d23239518994400006e7739ad310389#diff-9a9569e9d73f33740eada95275da7f30R3)

**Comment by profeIAP** [comment]
@YellowZaki por coherencia con el resto de funciones que tenemos, procura denominar **idLista** al parámetro que recibe la función

**Comment by profeIAP** [comment]
Perfecto, gracias
